### PR TITLE
fix: Issue 25 fix infinite spinning wheel

### LINKED ISSUE #25: Updating registration ends in infinite spinning wheel
If you update your registration, using the link from the mail, it will succeed but the website keeps on loading the window endlessly.

### PR DESCRIPTION
**Pull request by EduardSchwarzkopf**
Fixes #25 

- adds error handling

### CODE REVIEW

File: components/ParticipantFormUpdate.tsx [hunk 1]
```diff
@@ -29,12 +30,27 @@ export default function ParticipantFormUpdate({
...
+      setIsFailed(true);
+      await redirectAfterTimeout(timeout, path);
+    }
+  };
+
+  const redirectAfterTimeout = async (timeout: number, path: string) => {
+    await new Promise((resolve) => setTimeout(resolve, timeout));
+    setIsFailed(false);
+    setIsSubmitted(false);
+    router.push(path);
```
Comment (makellner) [inline components/ParticipantFormUpdate.tsx:53]: I guess this can be a bit simplified:

```suggestion
    await new Promise((resolve) => {
      setTimeout(() => {
            setIsFailed(false);
            setIsSubmitted(false);
            router.push(path);
      }, timeout);
    });
```

Comment (EduardSchwarzkopf) [reply components/ParticipantFormUpdate.tsx]: yes you are right. But I've simplified it even further. There is no need to have this logic in its own function, because the redirect should be always at the end.
Maybe on a later stage we can redirect to the forms again, on an error, but as of right now, this is the current behaviour.

File: components/ParticipantFormUpdate.tsx [hunk 2]
```diff
@@ -29,10 +30,15 @@ export default function ParticipantFormUpdate({
...
     event.preventDefault();
-    await ParticipantService(eventId).update(participantData.id, data);
-    setIsSubmitted(true);
+
+    try {
+      await ParticipantService(eventId).update(participantData.id, data);
+      setIsSubmitted(true);
+    } catch (error) {
+      setIsFailed(true);
+    }
```
Comment (makellner) [inline components/ParticipantFormUpdate.tsx:39]: I see this as part of the setTimeout block, as you want to redirect the user after a certain time and not a certain time after the request, correct?

Comment (EduardSchwarzkopf) [reply components/ParticipantFormUpdate.tsx:39]: yessir!

**Review by makellner — APPROVED** [review]
